### ISSUE TITLE
tab completion doesn't work

### ISSUE THREAD

**Issue by yakir12** [fredrikekre/jlpkg#18]
for me. I tried `jlpkg --project=` and then `<TAB>` inside a folder with a `toml` file, but nada. I tried a few other obvious things, but alas. I have `jlpkg v1.3.2` installed (via Julia, not the tarball). I already have `bash-completion` installed, or is that the problem? 

```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen Threadripper 2950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_NUM_THREADS = 16
```

**Comment by fredrikekre** [comment]
Do any completions work or is it specifically after `--project`?

**Comment by yakir12** [comment]
No, none of the examples you gave in the [Discourse post](https://discourse.julialang.org/t/jlpkg-a-command-line-interface-to-pkg/24077/2?u=yakir12) work.

**Comment by fredrikekre** [comment]
Then it seems like it didn't install correctly. Can you check if you have something like this
```
# Bash completion for jlpkg
if [[ -f ~/.bash_completion.d/jlpkg-completion.bash ]]; then
    . ~/.bash_completion.d/jlpkg-completion.bash
fi
```
in your bashrc file for example? And that the file `~/.bash_completion.d/jlpkg-completion.bash` exists.

**Comment by yakir12** [comment]
I don't have that file. Wait, installing this changes my bashrc? I just added `.julia/bin` to my path in my bashrc.

**Comment by yakir12** [comment]
```
yakir@eira:~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.2 (2020-09-23)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [12aac903] BinaryBuilder v0.2.6
  [89398ba2] LocalRegistry v0.3.0
  [14b8a8f1] PkgTemplates v0.7.13
  [c46f51b8] ProfileView v0.6.7
  [295af30f] Revise v3.1.6
  [c4c688b2] jlpkg v1.3.2

julia> import jlpkg; jlpkg.install(force=true)
[ Info: Installed jlpkg to `~/.julia/bin/jlpkg`.

julia> 
yakir@eira:~$ ls .bash*
.bash_history  .bash_logout  .bashrc
```

**Comment by fredrikekre** [comment]
The completions is a separate thing; `jlpkg.install_completion`.

**Comment by yakir12** [comment]
facepalm, as explained here:
https://github.com/fredrikekre/jlpkg#install-shell-completion
sorry for the noise and thank you for the package!
