### ISSUE TITLE
How to add the path?

### ISSUE THREAD

**Issue by zdlspace0528** [fredrikekre/jlpkg#24]
```
julia> import jlpkg;jlpkg.install()
[ Info: Installed jlpkg to `~/.julia/bin/jlpkg`.
┌ Warning: `Sys.which("jlpkg")` returns `nothing`, meaning that `command`
│ can not be found in PATH. Either make sure that `/Users/zhangdeliang/.julia/bin` is in PATH,
│ or manually add a symlink from a directory in PATH to the installed
│ program file.
│ Path to installed program:
│     /Users/zhangdeliang/.julia/bin/jlpkg
└ @ jlpkg ~/.julia/packages/jlpkg/ZwCoa/src/jlpkg.jl:72
```
How to set the path?

**Comment by fredrikekre** [comment]
Hi, didn't notice this issue until now.

Adding a folder to `PATH` is typically done in your shell startup configuration, (`~/.bashrc` for Bash, `~/.zshrc` for Zsh, etc..). For example you can put this in that file to prepend the `.julia/bin` folder to the existing `PATH`:
```
PATH="${HOME}/.julia/bin:${PATH}"
export PATH
```

Note that, if you prefer, you can install the file to a folder that already exist in `PATH` (you can see the existing directories in path by `echo ${PATH}` in the shell). You do this by passing the `destdir` keyword argument to `jlpkg.install`.
